name: Run
on:
  push
permissions:
  id-token: write
  contents: read
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: {distribution: temurin, java-version: 17}
      - name: Get JWT token
        run: |
          TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV
      - name: Build maven-server
        run: cd maven-server && mvn package
      - name: Build hello-world-app
        run: cd hello-world-app && mvn package
      - name: Run maven-server
        run: cd maven-server && java -jar target/maven-server-1.0.0.jar & sleep 10
      - name: Deploy hello-world-app
        run: cd hello-world-app && mvn deploy -s settings.xml
      - name: Stop maven-server
        run: pgrep -f maven-server && pkill -f maven-server
      - name: Discovery artifacts and tokens
        run: find maven-server/repo && cat maven-server/repo/jwt:1.txt | jq
