name: Run
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: {distribution: temurin, java-version: 17}
      - run: cd maven-server && mvn package
      - run: cd hello-world-app && mvn package
      - run: cd maven-server && java -jar target/maven-server-1.0.0.jar & sleep 10
      - run: cd hello-world-app && mvn deploy -DaltDeploymentRepository=repo::default::http://localhost:8080/repo
      - run: pgrep -f maven-server && pkill -f maven-server
      - run: find maven-server/repo
